[package]
name = "dnsupdater"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = "0.11"
tokio = { version = "1", features = ["full"] }
config = "0.10"
ipnetwork = "0.20.0"
toml = "0.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
dirs = "3.0"
get_if_addrs = "0.5"
